package br.dev.rvz.pombo.enumarations;

public enum Recado {
	DISPONIVEL,
	OCUPADO,
	NA_ESCOLA,
	NO_CINEMA,
	NO_TRABALHO,
	BATERIA_PRESTES_A_ACABAR,
	NAO_POSSO_FALAR_SOMENTE_MENSAGEM,
	EM_REUNIAO,
	NA_ACADEMIA,
	DORMINDO,
	SO_CHAMADA_URGENTE;

}
